name: money_mate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "C:/Users/user/StudioProjects/money_mate/lib/assets/final-image.jpg"
  min_sdk_android: 21

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0 # Corrected indentation

  cupertino_icons: ^1.0.6

  firebase_auth: ^5.1.2
  firebase_core: ^3.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1
  local_auth: ^2.2.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^5.0.1
  image_picker: ^1.0.7
  firebase_storage: ^12.0.0
  share_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  http: ^1.1.0

flutter:
  uses-material-design: true